ddd = ["s", "q", "r", "t", "z", "y"]
print(ddd)
#x = input("Видить букву:")
#ddd.remove(x)
#print(ddd)
# ddd.sort(reverse=True)
# print(sorted(ddd, reverse=True))
d = len(ddd)
print(d)
b = ddd.count("s")
print(b)